project:
  type: website
  output-dir: docs
  
website:
  title: "Chris Wojan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me 
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Outreach
      
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

