project:
  type: website
  output-dir: docs
  
website:
  title: "Chris Wojan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me 
      - text: Games
        menu: 
          - href: forests_foragers.qmd
            text: Forests and Foragers
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

